name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testing:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         python-version: ["3.7", "3.8", "3.9", "3.10"]
         jax-or-not: ["jax", "numpy"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.2.0
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install pytest
        python -m pip install .

    - name: Install JAX
      run: |
        if [[ ${{ matrix.jax-or-not }} == "jax" ]]; then
          python -m pip install jax jaxlib
        else
          python -m pip install numpy
        fi
    - name: Test with pytest
      run: |
        HS_BACKEND=${{ matrix.jax-or-not }} pytest